### ISSUE TITLE
大佬，运行好像有问题的么

### ISSUE THREAD

**Issue by unicorn357** [abeelan/jdSeckill#1]

**Comment by abeelan** [comment]
嗯？ 具体什么问题呢？更到最新看看。

**Comment by Jerey-Jobs** [comment]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import logger
  File "/Users/github/MaoTai/jdSeck0131/jdSeckill/logger.py", line 32, in <module>
    set_logger()
  File "/Users//github/MaoTai/jdSeck0131/jdSeckill/logger.py", line 27, in set_logger
    log_filename, when="D", interval=1, backupCount=5, encoding="utf-8")
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 200, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xiamin/github/MaoTai/jdSeck0131/jdSeckill/log/output.log'

**Comment by abeelan** [comment]
2.1 日起，关闭 web 抢购通道。
